In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
import os
print (os.listdir())

['.ipynb_checkpoints', '50startups.csv', 'gradientDescent.ipynb', 'LinearReg.ipynb', 'studentscores.csv']


In [36]:
dataset=pd.read_csv('50startups.csv')
X=dataset.iloc[ : , : -1].values
Y=dataset.iloc[ : ,-1].values
print(X)

[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]
 [101913.08 110594.11 229160.95]
 [100671.96  91790.61 249744.55]
 [ 93863.75 127320.38 249839.44]
 [ 91992.39 135495.07 252664.93]
 [119943.24 156547.42 256512.92]
 [114523.61 122616.84 261776.23]
 [ 78013.11 121597.55 264346.06]
 [ 94657.16 145077.58 282574.31]
 [ 91749.16 114175.79 294919.57]
 [ 86419.7  153514.11      0.  ]
 [ 76253.86 113867.3  298664.47]
 [ 78389.47 153773.43 299737.29]
 [ 73994.56 122782.75 303319.26]
 [ 67532.53 105751.03 304768.73]
 [ 77044.01  99281.34 140574.81]
 [ 64664.71 139553.16 137962.62]
 [ 75328.87 144135.98 134050.07]
 [ 72107.6  127864.55 353183.81]
 [ 66051.52 182645.56 118148.2 ]
 [ 65605.48 153032.06 107138.38]
 [ 61994.4

In [37]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2, random_state=0)


In [39]:
regressor.fit(X_train,Y_train) #we are training the model

LinearRegression()

In [40]:
y_pred=regressor.predict(X_test)
print(y_pred)

[103901.8969696  132763.05993126 133567.90370044  72911.78976736
 179627.92567224 115166.64864795  67113.5769057   98154.80686776
 114756.11555221 169064.01408795]


In [44]:
for i,(pred, actual) in enumerate(zip(y_pred, Y_test)):
    print(f"Sample{i+1}: Predicted = {pred:.2f}, Actual = {actual:.2f}")

Sample1: Predicted = 103901.90, Actual = 103282.38
Sample2: Predicted = 132763.06, Actual = 144259.40
Sample3: Predicted = 133567.90, Actual = 146121.95
Sample4: Predicted = 72911.79, Actual = 77798.83
Sample5: Predicted = 179627.93, Actual = 191050.39
Sample6: Predicted = 115166.65, Actual = 105008.31
Sample7: Predicted = 67113.58, Actual = 81229.06
Sample8: Predicted = 98154.81, Actual = 97483.56
Sample9: Predicted = 114756.12, Actual = 110352.25
Sample10: Predicted = 169064.01, Actual = 166187.94


In [42]:
#you cant directly print the o/p since its 4D since 3 features of i/p and 1 o/p

In [43]:
print("Coefficients:" , regressor.coef_)
print("Intercept:", regressor.intercept_)

Coefficients: [0.77884104 0.0293919  0.03471025]
Intercept: 42989.00816508669
